### PR TITLE
[MOD-15934] aggregate.h: use __atomic_*_n builtins instead of <stdatomic.h>

### PR DESCRIPTION
**Pull request by lerman25**
## Describe the changes in the pull request

Fixes [MOD-15934](https://redislabs.atlassian.net/browse/MOD-15934).

1. **Current**: src/aggregate/aggregate.h (added in #9749) inlines AREQ_TimedOut / AREQ_SetTimedOut, whose bodies expand to atomic_load_explicit / atomic_store_explicit from stdatomic.h. Because aggregate.h is transitively reachable from the FFI headers bindgen parses, **libclang must successfully type-check those inline bodies**.
2. **Change**: Replace the stdatomic.h macros with __atomic_load_n / __atomic_store_n compiler builtins (no header required). A (bool *) cast strips _Atomic so clang strict __atomic_*_n accepts the pointer; the macros are only used on bool fields (timedOut, aggregatingResults). The _Atomic qualifier on the struct fields is **kept**, so type-checker enforcement is unchanged.
3. **Outcome**: The header parses cleanly under libclang-14 and the ce-testing packaging pipeline unblocks. Codegen is byte-identical (single-byte mov, no lock prefix on relaxed ops).

#### Background

Our CI forces LLVM 21 via .install/install_llvm.sh, which is why the regression was not caught here. The [ce-testing nightly run](https://github.com/redislabsdev/ce-testing/actions/runs/26490737083) uses each distro stock toolchain — Ubuntu 22.04 ships **libclang-14**, which cannot resolve atomic_load_explicit / memory_order_relaxed during the bindgen parse:

    /usr/include/.../stdatomic.h:... use of undeclared identifier atomic_load_explicit

A follow-up PR will add a small CI job that runs the FFI bindgen step against the distro stock libclang to prevent recurrence.

#### Which additional issues this PR fixes
1. Regression introduced by #9749
2. Unblocks ce-testing nightly: https://github.com/redislabsdev/ce-testing/actions/runs/26490737083

#### Main objects this PR modified
1. src/aggregate/aggregate.h — RS_AtomicLoadRelaxed / RS_AtomicStoreRelaxed macros

#### Mark if applicable

- [ ] This PR introduces API changes
- [ ] This PR introduces serialization changes

#### Release Notes

- [ ] This PR requires release notes
- [x] This PR does not require release notes

Build-system / packaging fix only. Released module behavior, on-disk format, and public API are unchanged.

---
Co-authored by [Augment Code](https://www.augmentcode.com/?utm_source=github&utm_medium=pr&utm_campaign=redisearch)

[MOD-15934]: https://redislabs.atlassian.net/browse/MOD-15934?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by lerman25** [comment]
Addressed both review comments in 8d6270b59:

- **Codex P1 (aggregate.h:39)**: Added `#include <stdatomic.h>` directly to `aggregate_request.c`, which uses `atomic_load_explicit`, `atomic_compare_exchange_strong_explicit`, and `memory_order_relaxed` and previously relied on the transitive include through `aggregate.h`.
- **Cursor Bugbot (aggregate.h:37-39)**: Removed the hardcoded `(bool *)` cast from the C-path macros. The `__atomic_*_n` builtins are type-generic over integral scalar / pointer types (including `_Atomic`-qualified ones), so the cast was unnecessary and would have silently truncated future non-`bool` `RS_Atomic(T)` uses (e.g. `RS_Atomic(size_t)` in `disk_gc.h`).

Verified locally that `__atomic_load_n` / `__atomic_store_n` compile cleanly under `gcc -Wall -Wextra -Werror` (both default and `-std=c99`) on `_Atomic(bool)*` and `_Atomic(size_t)*` without any cast.

**Review by GuyAv46 — APPROVED** [review]
